name: aws-hello-world-ubuntu
label: AWS Ubuntu Hello World
description: Builds a single Ubuntu Server in AWS

type: terraform
extends:

labels:
  service_type: aws_terraform

# These variables will be presented to the operator in pan-cnc enabled tools
# the values of which will be passed to terraform via cli options. The name
# of these variables *must* match the variables defined in variables.tf
variables:
  - name: access_key
    description: AWS Access Key
    default: Place your Access Key
    type_hint: text
  - name: secret_key
    description: AWS Secret Key
    default:
    type_hint: password
  - name: region
    description: AWS Region
    default: us-east-2
    type_hint: text
